CREATE TABLE user_keys
(
	id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	user_id VARCHAR(15) NOT NULL,
	pub_key VARCHAR(256) NOT NULL,
	created_date DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);
